name: "Test"

on: [push, pull_request]

jobs:
  test:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Test build current
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --all \
            --target grott-current \
            --docker-hub egguy
  publish:
    needs: test
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target grott-current \
            --docker-hub user-name-or-space-name